Shoot speaker from base
frc2357/FRC-2024 pull request #109
Opened 2024-02-21 00:16 UTC by PureBreadCat

fixes issue #71

2024-02-21 16:46 UTC, Tyson453 requested changes

2024-02-21 16:46 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/commands/scoring/SpeakerScoreFromBase.java
> +        new IntakeStop(),
You don't need to have the `IntakeStop()` command here. Using `.withTimeout()` interrupts the `IntakeFeedToShooter` command which stops the motors once it ends

2024-02-21 16:46 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/commands/scoring/SpeakerScoreFromBase.java
> +                SHOOTER.BOTTOM_MOTOR_SPEAKER_SCORE_FROM_BASE_RPMS)),
Not super important but the base of the speaker is called the "Subwoofer" so you could shorten the names of these variables to something like "TOP_MOTOR_SUBWOOFER_SHOT_RPMS"

2024-02-23 00:26 UTC, NolanCampbell2357 requested changes

2024-02-23 00:26 UTC, NolanCampbell2357 commented on robotbase/src/main/java/frc/robot/commands/source/SourceIntakeFromShooter.java
> +public class SourceIntakeFromShooter extends SequentialCommandGroup {
This needs to be a ParallelDeadlineGroup

2024-02-23 01:30 UTC, NolanCampbell2357 approved these changes

2024-02-23 01:30 UTC, merged