Added one of the two commands, the shooter intake command
frc2357/FRC-2024 pull request #89
Opened 2024-02-10 20:49 UTC by PureBreadCat

fixes #78

2024-02-10 20:55 UTC, NolanCampbell2357 requested changes

2024-02-10 20:55 UTC, NolanCampbell2357 commented on robotbase/src/main/java/frc/robot/commands/pickup/ShooterIntakeFromSource.java
> +        Robot.pivot.setPivotRotations(Constants.SHOOTER_PIVOT.INTAKE_FROM_SOURCE_ROTATIONS);
This should be done using a parallel command group with commands specifically for each subsystem. We should never directly interact with multiple subsystems in a single command.

2024-02-10 22:32 UTC, Tyson453 requested changes

2024-02-10 22:32 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/Constants.java
> +    public static final double BOTTOM_MOTOR_PICKUP_SPEED_RPMS = 0;
rename to `TOP_MOTOR_SOURCE_INTAKE_RPMS`

2024-02-10 22:32 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/Constants.java
> +    public static final double BOTTOM_MOTOR_EAT_SPEED_PERCENT_OUTPUT = 0;
rename to `TOP_MOTOR_SOURCE_INTAKE_SPEED_PERCENT_OUTPUT`

2024-02-10 22:32 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/commands/intake/IntakeNoteFromSource.java
> +package frc.robot.commands.intake;
Rename command to `IntakeReverseFeed`

2024-02-10 22:32 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/commands/pivot/ShooterPivotIntakeFromSource.java
> +package frc.robot.commands.pivot;
This is fine for now. Eventually we'll have a command that will just set the rotations that are passed into the command (I haven't done that yet).

2024-02-10 22:32 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/commands/pivot/ShooterPivotIntakeFromSource.java
> +    return false;
`return Robot.pivot.isPivotAtRotations()`

2024-02-10 22:32 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/commands/pickup/ShooterIntakeFromSource.java
> +package frc.robot.commands.pickup;
Rename to `SourceIntakeFromShooter`

2024-02-10 22:32 UTC, Tyson453 commented on robotbase/src/main/java/frc/robot/commands/shooter/ShooterPickupFromSource.java
> +package frc.robot.commands.shooter;
This is fine for now. Eventually we'll have a command that sets the RPMs (I haven't done that yet). I'll fix this in my branch.

2024-02-11 15:32 UTC, NolanCampbell2357 requested changes

2024-02-11 15:32 UTC, NolanCampbell2357 commented on robotbase/src/main/java/frc/robot/Constants.java
> +    public static final double TOP_MOTOR_SOURCE_INTAKE_RPMSS = 0;
Extra S

2024-02-11 15:32 UTC, NolanCampbell2357 commented on robotbase/src/main/java/frc/robot/commands/intake/IntakeReverseFeed.java
> +        -Constants.INTAKE.TOP_MOTOR_SOURCE_INTAKE_SPEED_PERCENT_OUTPUT,
Pullin the constants file like this `frc.robot.Constants.*` so you do not need toreference `Constant` everytime.

2024-02-11 18:58 UTC, NolanCampbell2357 approved these changes

2024-02-11 19:31 UTC, merged